version: '3'

services: 
  app:
    build: ./
    ports:
      - "4000:4000"
    volumes: 
      - ./:/app
      #- /app/node_modules
    restart: on-failure 
    links: 
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123@34578.as'
      PORT: '4000'
    entrypoint: ./entrypoint2.sh

  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123@34578.as'
      MYSQL_DATABASE: 'app'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d